### ISSUE TITLE
unnecessary (duplicate) packages 

### ISSUE THREAD

**Issue by tobwen** [PDOK/mapproxy-docker#11]
You're currently mixing the distribution's _Python_ packages with the _PIP_ ones:
- `python3-pil` = `Pillow` (needs some libraries as dependencies)
- `python3-yaml` = `PyYAML`
- `python3-shapely` = `Shapely`
- Also, neither `python3-virtualenv` isn't needed, nor `eventlet gunicorn` is.

Installing the distro's packages make it easier to get all the dependencies, but I think they are better ways in Debian.

I'll try to fix it and send you a PR in return for your good work so far.

**Comment by WouterVisscher** [comment]
Sorry @tobwen, couldn't wait :)
So I presume you mean it like this -> https://github.com/PDOK/mapproxy-docker/pull/12
And let pip handle all the dependencies regarding python

**Comment by WouterVisscher** [comment]
We made some improvements (cleaned up) regrading the duplicate packages in #12
