### ISSUE TITLE
Container contains two Python versions

### ISSUE THREAD

**Issue by tobwen** [PDOK/mapproxy-docker#9]
Currently, the container will contain at least two different versions of _Python_.

You're starting off `python:3.7-slim-buster` container, which doesn't contain a _Debian_ managed _Python 3_. Since you're installing `python-*` instead of `python3-*`, _apt_ pulls _Python 2_ packages and its runtime.

Even when forcing the installation of `python3-*` packages, _apt_ doesn't recognize the manually installed _Python 3_ from the container image and it will additionally install the maintained one.

Better start off `debian:buster-slim` - this will save the space of the never used runtimes from `python:3.7-slim-buster`

**Comment by WouterVisscher** [comment]
@tobwen good catch!
We are working on it -> https://github.com/PDOK/mapproxy-docker/pull/10

**Comment by WouterVisscher** [comment]
@tobwen we have made a new release https://github.com/PDOK/mapproxy-docker/releases/tag/1.12-patch1 and docker image: pdok/mapproxy:latest or pdok/mapproxy:1.12-patch1 on hub.docker
